alias: Awtrix Power Grid Export
description: ""
triggers:
  - trigger: time_pattern
    minutes: /5
conditions:
  - condition: numeric_state
    entity_id: sensor.pv_leistungpv_total_kw
    above: 0.1
  - condition: state
    entity_id: switch.ikea_steckdose_awtrix_wohnzimmer
    state:
      - "on"
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      payload: |
        {
            {% set power = states('sensor.solarnet_power_grid_export')|float  %}
            {% set text = ('%.2f' | format(power / 1000)) if power >= 0.01 else 'No feed-in'%}
            {% set icon = ('55396') if power >= 0.01 else ('71079') %}
            "text": "{{ text }}",
            "icon": "{{ icon }}",
            "rainbow": false,
            "duration": 10,
            "pushIcon": 0,
            "lifetime": 600,
            "repeat": 6
        }
      topic: awtrix_b3d1fc/custom/powergridexport
mode: single
