alias: Awtrix Power Consumed
description: ""
triggers:
  - trigger: time_pattern
    minutes: /5
conditions:
  - condition: state
    entity_id: switch.ikea_steckdose_awtrix_wohnzimmer
    state:
      - "on"
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      payload: >
        { "text": "{{ '%.2f' |
        format(states.sensor.solarnet_power_load_consumed.state | float / 1000)
        }}",
            "rainbow": false,
            "icon": "55395",
            "duration": 10,
            "pushIcon": 0,
            "lifetime": 2000,
            "repeat": 6
        }
      topic: awtrix_b3d1fc/custom/powerconsumed
mode: single
