alias: Awtrix Warmwasserinfo
description: ""
triggers:
  - trigger: time_pattern
    minutes: /5
conditions:
  - condition: numeric_state
    entity_id: sensor.boiler_reservoir_temp_tw1
    below: 40
  - condition: state
    entity_id: switch.ikea_steckdose_awtrix_wohnzimmer
    state:
      - "on"
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: 0
      retain: false
      payload: >
        { "text": "{{ '%.1f°C' |
        format(states.sensor.boiler_reservoir_temp_tw1.state | float )}}",
            "rainbow": false,
            "icon": "71109",
            "duration": 10,
            "pushIcon": 0,
            "lifetime": 400,
            "repeat": 6
        }
      topic: awtrix_b3d1fc/custom/waterinfos
mode: single
